-- Generated by packages/db/scripts/build-demo-seed.mjs: DEMO DATA, safe to re-run.
PRAGMA defer_foreign_keys = on;
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (1, 'pyjama-short-coton-fleuri', 'Pyjama short coton fleuri', 'بيجامة شورت قطن مزهرة', 'Débardeur + short en **coton léger**, imprimé fleuri.

- Frais et doux pour les nuits d''été
- Short à taille élastique
- Lavage à 30°', 'قميص بدون أكمام + شورت من **القطن الخفيف** بطبعة زهور.

- منعش وناعم لليالي الصيف
- شورت بخصر مطاطي
- غسيل على 30 درجة', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas-ete'), '["nouveaute"]', 2900, NULL, 1400, 0, 1791028500676, 1791028500676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (1, 1, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (1, 1, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (2, 1, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (3, 1, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (4, 1, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (2, 1, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (5, 2, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (6, 2, 'Bleu ciel', 'أزرق سماوي', '#a9c8e8', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (1, 1, 'PYJSHOCOT-ROSE-S', '[1,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (2, 1, 'PYJSHOCOT-ROSE-M', '[2,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (3, 1, 'PYJSHOCOT-ROSE-L', '[3,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (4, 1, 'PYJSHOCOT-ROSE-XL', '[4,5]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (5, 1, 'PYJSHOCOT-CIEL-S', '[1,6]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (6, 1, 'PYJSHOCOT-CIEL-M', '[2,6]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (7, 1, 'PYJSHOCOT-CIEL-L', '[3,6]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (8, 1, 'PYJSHOCOT-CIEL-XL', '[4,6]', 2, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (2, 'ensemble-satin-ete-lina', 'Ensemble satin d''été Lina', 'طقم ساتان صيفي لينا', 'Chemise manches courtes + short en **satin fluide**, passepoil contrasté.', 'قميص بأكمام قصيرة + شورت من **الساتان الناعم** بحواف متباينة.', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas-ete'), '[]', 3800, 4500, 1900, 1, 1789041300676, 1789041300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (3, 2, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (7, 3, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (8, 3, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (9, 3, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (10, 3, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (4, 2, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (11, 4, 'Champagne', 'شمبانيا', '#e9d3b0', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (12, 4, 'Lavande', 'لافندر', '#b9a7d6', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (9, 2, 'ENSSATETE-CHAMPAGNE-S', '[7,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (10, 2, 'ENSSATETE-CHAMPAGNE-M', '[8,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (11, 2, 'ENSSATETE-CHAMPAGNE-L', '[9,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (12, 2, 'ENSSATETE-CHAMPAGNE-XL', '[10,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (13, 2, 'ENSSATETE-LAVANDE-S', '[7,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (14, 2, 'ENSSATETE-LAVANDE-M', '[8,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (15, 2, 'ENSSATETE-LAVANDE-L', '[9,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (16, 2, 'ENSSATETE-LAVANDE-XL', '[10,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (3, 'pyjama-polaire-douceur', 'Pyjama polaire Douceur', 'بيجامة صوف ناعمة', 'Pyjama en **polaire très douce**, haut à col rond et pantalon chaud.

- Idéal pour les nuits froides
- Ne bouloche pas', 'بيجامة من **الصوف الناعم جدا**، قميص بياقة دائرية وسروال دافئ.

- مثالية لليالي الباردة
- لا تتكور', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas-hiver'), '["nouveaute"]', 4200, NULL, 2100, 2, 1790682900676, 1790682900676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (5, 3, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (13, 5, 'M', 'M', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (14, 5, 'L', 'L', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (15, 5, 'XL', 'XL', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (16, 5, 'XXL', 'XXL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (6, 3, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (17, 6, 'Bordeaux', 'خمري', '#6d1f33', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (18, 6, 'Gris chiné', 'رمادي', '#9a9a9e', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (17, 3, 'PYJPOLDOU-BORDEAUX-M', '[13,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (18, 3, 'PYJPOLDOU-BORDEAUX-L', '[14,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (19, 3, 'PYJPOLDOU-BORDEAUX-XL', '[15,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (20, 3, 'PYJPOLDOU-BORDEAUX-XXL', '[16,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (21, 3, 'PYJPOLDOU-GRIS-M', '[13,18]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (22, 3, 'PYJPOLDOU-GRIS-L', '[14,18]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (23, 3, 'PYJPOLDOU-GRIS-XL', '[15,18]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (24, 3, 'PYJPOLDOU-GRIS-XXL', '[16,18]', 5, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (4, 'pyjama-velours-cosy', 'Pyjama velours Cosy', 'بيجامة قطيفة دافئة', 'Ensemble en **velours côtelé** doux, chaud et élégant à la maison.', 'طقم من **القطيفة الناعمة**، دافئ وأنيق في البيت.', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas-hiver'), '[]', 4500, 5500, 2300, 3, 1787745300676, 1787745300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (7, 4, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (19, 7, 'M', 'M', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (20, 7, 'L', 'L', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (21, 7, 'XL', 'XL', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (8, 4, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (22, 8, 'Noir', 'أسود', '#1f1a1c', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (23, 8, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (25, 4, 'PYJVELCOS-NOIR-M', '[19,22]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (26, 4, 'PYJVELCOS-NOIR-L', '[20,22]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (27, 4, 'PYJVELCOS-NOIR-XL', '[21,22]', 1, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (28, 4, 'PYJVELCOS-ROSE-M', '[19,23]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (29, 4, 'PYJVELCOS-ROSE-L', '[20,23]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (30, 4, 'PYJVELCOS-ROSE-XL', '[21,23]', 1, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (5, 'robe-de-chambre-satin-yasmine', 'Robe de chambre satin Yasmine', 'روب دو شامبر ساتان ياسمين', 'Robe de chambre longue en **satin**, ceinture à nouer et manches évasées.', 'روب دو شامبر طويل من **الساتان**، بحزام للربط وأكمام واسعة.', 'published', (SELECT id FROM categories WHERE slug = 'robes-de-chambre-nuisettes'), '["nouveaute"]', 4900, NULL, 2400, 4, 1790942100676, 1790942100676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (9, 5, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (24, 9, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (25, 9, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (26, 9, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (27, 9, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (10, 5, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (28, 10, 'Champagne', 'شمبانيا', '#e9d3b0', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (29, 10, 'Bordeaux', 'خمري', '#6d1f33', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (31, 5, 'ROBDECHAS-CHAMPAGNE-S', '[24,28]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (32, 5, 'ROBDECHAS-CHAMPAGNE-M', '[25,28]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (33, 5, 'ROBDECHAS-CHAMPAGNE-L', '[26,28]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (34, 5, 'ROBDECHAS-CHAMPAGNE-XL', '[27,28]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (35, 5, 'ROBDECHAS-BORDEAUX-S', '[24,29]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (36, 5, 'ROBDECHAS-BORDEAUX-M', '[25,29]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (37, 5, 'ROBDECHAS-BORDEAUX-L', '[26,29]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (38, 5, 'ROBDECHAS-BORDEAUX-XL', '[27,29]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (6, 'nuisette-dentelle-amira', 'Nuisette dentelle Amira', 'قميص نوم دانتيل أميرة', 'Nuisette **satinée** à fines bretelles réglables, bordure en dentelle.', 'قميص نوم **ساتان** بحمالات رفيعة قابلة للتعديل وحواف من الدانتيل.', 'published', (SELECT id FROM categories WHERE slug = 'robes-de-chambre-nuisettes'), '[]', 2500, 3200, 1000, 5, 1788609300676, 1788609300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (11, 6, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (30, 11, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (31, 11, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (32, 11, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (12, 6, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (33, 12, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (34, 12, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (39, 6, 'NUIDENAMI-ROSE-S', '[30,33]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (40, 6, 'NUIDENAMI-ROSE-M', '[31,33]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (41, 6, 'NUIDENAMI-ROSE-L', '[32,33]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (42, 6, 'NUIDENAMI-NOIR-S', '[30,34]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (43, 6, 'NUIDENAMI-NOIR-M', '[31,34]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (44, 6, 'NUIDENAMI-NOIR-L', '[32,34]', 3, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (7, 'ensemble-dentelle-rose', 'Ensemble dentelle Rose', 'طقم دانتيل روز', 'Soutien-gorge + culotte en **dentelle délicate**. Livré dans un emballage discret.', 'حمالة صدر + سروال داخلي من **الدانتيل الرقيق**. يصلك في تغليف سري.', 'published', (SELECT id FROM categories WHERE slug = 'ensembles-lingerie'), '["nouveaute"]', 2900, NULL, 1200, 6, 1791114900676, 1791114900676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (13, 7, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (35, 13, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (36, 13, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (37, 13, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (14, 7, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (38, 14, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (39, 14, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (45, 7, 'ENSDENROS-ROSE-S', '[35,38]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (46, 7, 'ENSDENROS-ROSE-M', '[36,38]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (47, 7, 'ENSDENROS-ROSE-L', '[37,38]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (48, 7, 'ENSDENROS-NOIR-S', '[35,39]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (49, 7, 'ENSDENROS-NOIR-M', '[36,39]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (50, 7, 'ENSDENROS-NOIR-L', '[37,39]', 5, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (8, 'ensemble-satin-nour', 'Ensemble satin Nour', 'طقم ساتان نور', 'Ensemble **satin et tulle**, armatures souples, très confortable.', 'طقم من **الساتان والتول**، بأسلاك مرنة ومريح جدا.', 'published', (SELECT id FROM categories WHERE slug = 'ensembles-lingerie'), '[]', 3300, NULL, 1500, 7, 1789473300676, 1789473300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (15, 8, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (40, 15, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (41, 15, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (42, 15, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (16, 8, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (43, 16, 'Champagne', 'شمبانيا', '#e9d3b0', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (44, 16, 'Bordeaux', 'خمري', '#6d1f33', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (51, 8, 'ENSSATNOU-CHAMPAGNE-S', '[40,43]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (52, 8, 'ENSSATNOU-CHAMPAGNE-M', '[41,43]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (53, 8, 'ENSSATNOU-CHAMPAGNE-L', '[42,43]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (54, 8, 'ENSSATNOU-BORDEAUX-S', '[40,44]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (55, 8, 'ENSSATNOU-BORDEAUX-M', '[41,44]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (56, 8, 'ENSSATNOU-BORDEAUX-L', '[42,44]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (9, 'soutien-gorge-confort', 'Soutien-gorge confort sans armatures', 'حمالة صدر مريحة بدون سلك', 'Soutien-gorge **sans armatures**, bonnets moulés, invisible sous les vêtements.', 'حمالة صدر **بدون سلك**، بأكواب مقولبة، لا تظهر تحت الملابس.', 'published', (SELECT id FROM categories WHERE slug = 'soutiens-gorge-culottes'), '[]', 1600, NULL, 650, 8, 1790164500676, 1790164500676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (17, 9, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (45, 17, '85B', '85B', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (46, 17, '90B', '90B', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (47, 17, '95C', '95C', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (48, 17, '100C', '100C', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (18, 9, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (49, 18, 'Nude', 'بيج', '#d9b8a3', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (50, 18, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (57, 9, 'SOUGORCON-NUDE-85B', '[45,49]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (58, 9, 'SOUGORCON-NUDE-90B', '[46,49]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (59, 9, 'SOUGORCON-NUDE-95C', '[47,49]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (60, 9, 'SOUGORCON-NUDE-100C', '[48,49]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (61, 9, 'SOUGORCON-NOIR-85B', '[45,50]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (62, 9, 'SOUGORCON-NOIR-90B', '[46,50]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (63, 9, 'SOUGORCON-NOIR-95C', '[47,50]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (64, 9, 'SOUGORCON-NOIR-100C', '[48,50]', 6, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (10, 'lot-3-culottes-coton', 'Lot de 3 culottes coton', '3 سراويل داخلية قطنية', 'Trois culottes en **coton doux**, coutures plates, pour tous les jours.', 'ثلاثة سراويل داخلية من **القطن الناعم**، بخياطة مسطحة، لكل يوم.', 'published', (SELECT id FROM categories WHERE slug = 'soutiens-gorge-culottes'), '[]', 1200, 1500, 450, 9, 1788177300676, 1788177300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (19, 10, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (51, 19, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (52, 19, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (53, 19, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (54, 19, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (20, 10, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (55, 20, 'Blanc', 'أبيض', '#f7f3ee', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (56, 20, 'Nude', 'بيج', '#d9b8a3', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (65, 10, 'LOT3CULCO-BLANC-S', '[51,55]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (66, 10, 'LOT3CULCO-BLANC-M', '[52,55]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (67, 10, 'LOT3CULCO-BLANC-L', '[53,55]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (68, 10, 'LOT3CULCO-BLANC-XL', '[54,55]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (69, 10, 'LOT3CULCO-NUDE-S', '[51,56]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (70, 10, 'LOT3CULCO-NUDE-M', '[52,56]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (71, 10, 'LOT3CULCO-NUDE-L', '[53,56]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (72, 10, 'LOT3CULCO-NUDE-XL', '[54,56]', 8, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (11, 'gaine-taille-haute', 'Gaine gainante taille haute', 'مشد البطن بخصر عالٍ', 'Gaine **taille haute** qui affine la silhouette, sans couture visible.', 'مشد **بخصر عالٍ** ينحف القوام، بدون خياطة ظاهرة.', 'published', (SELECT id FROM categories WHERE slug = 'gaines'), '[]', 2700, NULL, 1100, 10, 1790510100676, 1790510100676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (21, 11, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (57, 21, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (58, 21, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (59, 21, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (60, 21, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (22, 11, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (61, 22, 'Nude', 'بيج', '#d9b8a3', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (62, 22, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (73, 11, 'GAITAIHAU-NUDE-S', '[57,61]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (74, 11, 'GAITAIHAU-NUDE-M', '[58,61]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (75, 11, 'GAITAIHAU-NUDE-L', '[59,61]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (76, 11, 'GAITAIHAU-NUDE-XL', '[60,61]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (77, 11, 'GAITAIHAU-NOIR-S', '[57,62]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (78, 11, 'GAITAIHAU-NOIR-M', '[58,62]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (79, 11, 'GAITAIHAU-NOIR-L', '[59,62]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (80, 11, 'GAITAIHAU-NOIR-XL', '[60,62]', 5, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (12, 'body-sculptant-invisible', 'Body sculptant invisible', 'بودي مشد غير مرئي', 'Body **sculptant** à bretelles réglables, invisible sous une robe.', 'بودي **مشد** بحمالات قابلة للتعديل، لا يظهر تحت الفستان.', 'published', (SELECT id FROM categories WHERE slug = 'gaines'), '[]', 3200, NULL, 1400, 11, 1786881300676, 1786881300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (23, 12, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (63, 23, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (64, 23, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (65, 23, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (66, 23, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (24, 12, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (67, 24, 'Nude', 'بيج', '#d9b8a3', 0);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (81, 12, 'BODSCUINV-NUDE-S', '[63,67]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (82, 12, 'BODSCUINV-NUDE-M', '[64,67]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (83, 12, 'BODSCUINV-NUDE-L', '[65,67]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (84, 12, 'BODSCUINV-NUDE-XL', '[66,67]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (13, 'coffret-trousseau-lilia', 'Coffret trousseau Lilia (5 pièces)', 'طقم جهاز العروس ليليا (5 قطع)', 'Le coffret de la mariée : **robe de chambre, nuisette, 2 ensembles et pyjama**, dans une boîte cadeau.

- Couleurs assorties
- Emballage cadeau offert', 'طقم العروس: **روب دو شامبر، قميص نوم، طقمان داخليان وبيجامة** في علبة هدية.

- ألوان متناسقة
- تغليف هدية مجاني', 'published', (SELECT id FROM categories WHERE slug = 'trousseau-mariee'), '["nouveaute"]', 12900, NULL, 6500, 12, 1790855700676, 1790855700676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (25, 13, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (68, 25, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (69, 25, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (70, 25, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (26, 13, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (71, 26, 'Ivoire', 'عاجي', '#efe6d6', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (72, 26, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (85, 13, 'COFTROLIL-IVOIRE-S', '[68,71]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (86, 13, 'COFTROLIL-IVOIRE-M', '[69,71]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (87, 13, 'COFTROLIL-IVOIRE-L', '[70,71]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (88, 13, 'COFTROLIL-ROSE-S', '[68,72]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (89, 13, 'COFTROLIL-ROSE-M', '[69,72]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (90, 13, 'COFTROLIL-ROSE-L', '[70,72]', 2, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (14, 'ensemble-mariee-dentelle-blanche', 'Ensemble mariée dentelle blanche', 'طقم العروس دانتيل أبيض', 'Nuisette longue + robe de chambre en **dentelle blanche**, pour la nuit de noces.', 'قميص نوم طويل + روب دو شامبر من **الدانتيل الأبيض** لليلة العرس.', 'published', (SELECT id FROM categories WHERE slug = 'trousseau-mariee'), '[]', 6900, 7900, 3200, 13, 1787313300676, 1787313300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (27, 14, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (73, 27, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (74, 27, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (75, 27, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (28, 14, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (76, 28, 'Blanc', 'أبيض', '#f7f3ee', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (77, 28, 'Ivoire', 'عاجي', '#efe6d6', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (91, 14, 'ENSMARDEN-BLANC-S', '[73,76]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (92, 14, 'ENSMARDEN-BLANC-M', '[74,76]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (93, 14, 'ENSMARDEN-BLANC-L', '[75,76]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (94, 14, 'ENSMARDEN-IVOIRE-S', '[73,77]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (95, 14, 'ENSMARDEN-IVOIRE-M', '[74,77]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (96, 14, 'ENSMARDEN-IVOIRE-L', '[75,77]', 3, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (15, 'nuisette-longue-soie-layla', 'Nuisette longue soie Layla', 'قميص نوم طويل حرير ليلى', 'Nuisette longue **effet soie**, dos décolleté en dentelle.', 'قميص نوم طويل **بملمس الحرير**، بظهر مفتوح من الدانتيل.', 'published', (SELECT id FROM categories WHERE slug = 'lingerie-fine'), '["nouveaute"]', 5400, NULL, 2600, 14, 1790769300676, 1790769300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (29, 15, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (78, 29, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (79, 29, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (80, 29, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (30, 15, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (81, 30, 'Bordeaux', 'خمري', '#6d1f33', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (82, 30, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (97, 15, 'NUILONSOI-BORDEAUX-S', '[78,81]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (98, 15, 'NUILONSOI-BORDEAUX-M', '[79,81]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (99, 15, 'NUILONSOI-BORDEAUX-L', '[80,81]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (100, 15, 'NUILONSOI-NOIR-S', '[78,82]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (101, 15, 'NUILONSOI-NOIR-M', '[79,82]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (102, 15, 'NUILONSOI-NOIR-L', '[80,82]', 3, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (16, 'robe-nuit-satin-fendue', 'Robe de nuit satin fendue', 'فستان نوم ساتان بفتحة', 'Robe de nuit en **satin** fendue sur le côté, bretelles croisées.', 'فستان نوم من **الساتان** بفتحة جانبية وحمالات متقاطعة.', 'published', (SELECT id FROM categories WHERE slug = 'lingerie-fine'), '[]', 4800, NULL, 2200, 15, 1788782100676, 1788782100676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (31, 16, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (83, 31, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (84, 31, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (85, 31, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (32, 16, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (86, 32, 'Émeraude', 'زمردي', '#1f6f5c', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (87, 32, 'Champagne', 'شمبانيا', '#e9d3b0', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (103, 16, 'ROBNUISAT-EMERAUDE-S', '[83,86]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (104, 16, 'ROBNUISAT-EMERAUDE-M', '[84,86]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (105, 16, 'ROBNUISAT-EMERAUDE-L', '[85,86]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (106, 16, 'ROBNUISAT-CHAMPAGNE-S', '[83,87]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (107, 16, 'ROBNUISAT-CHAMPAGNE-M', '[84,87]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (108, 16, 'ROBNUISAT-CHAMPAGNE-L', '[85,87]', 3, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (17, 'survetement-molleton-sara', 'Survêtement molleton Sara', 'بدلة رياضية سارة', 'Sweat à capuche + jogging en **molleton doux**, coupe confortable.', 'سترة بقبعة + سروال رياضي من **القطن الصوفي الناعم**، بقصة مريحة.', 'published', (SELECT id FROM categories WHERE slug = 'sportswear-survetements'), '[]', 5900, NULL, 2900, 16, 1790423700676, 1790423700676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (33, 17, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (88, 33, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (89, 33, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (90, 33, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (91, 33, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (34, 17, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (92, 34, 'Gris chiné', 'رمادي', '#9a9a9e', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (93, 34, 'Bleu marine', 'كحلي', '#1f2a44', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (109, 17, 'SURMOLSAR-GRIS-S', '[88,92]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (110, 17, 'SURMOLSAR-GRIS-M', '[89,92]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (111, 17, 'SURMOLSAR-GRIS-L', '[90,92]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (112, 17, 'SURMOLSAR-GRIS-XL', '[91,92]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (113, 17, 'SURMOLSAR-MARINE-S', '[88,93]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (114, 17, 'SURMOLSAR-MARINE-M', '[89,93]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (115, 17, 'SURMOLSAR-MARINE-L', '[90,93]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (116, 17, 'SURMOLSAR-MARINE-XL', '[91,93]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (18, 'ensemble-legging-brassiere', 'Ensemble legging & brassière', 'طقم ليغينغ وصدرية رياضية', 'Legging **gainant** taille haute + brassière de sport, tissu respirant.', 'ليغينغ **مشد** بخصر عالٍ + صدرية رياضية، قماش يسمح بالتهوية.', 'published', (SELECT id FROM categories WHERE slug = 'sportswear-survetements'), '[]', 3900, 4600, 1800, 17, 1787918100676, 1787918100676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (35, 18, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (94, 35, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (95, 35, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (96, 35, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (36, 18, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (97, 36, 'Noir', 'أسود', '#1f1a1c', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (98, 36, 'Lavande', 'لافندر', '#b9a7d6', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (117, 18, 'ENSLEGBRA-NOIR-S', '[94,97]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (118, 18, 'ENSLEGBRA-NOIR-M', '[95,97]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (119, 18, 'ENSLEGBRA-NOIR-L', '[96,97]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (120, 18, 'ENSLEGBRA-LAVANDE-S', '[94,98]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (121, 18, 'ENSLEGBRA-LAVANDE-M', '[95,98]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (122, 18, 'ENSLEGBRA-LAVANDE-L', '[96,98]', 5, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (19, 'djebba-brodee-lilia', 'Djebba brodée Lilia', 'جبة مطرزة ليليا', 'Djebba longue et fluide, **broderie au col et aux manches**, coupe ample et confortable.

- Tissu léger, agréable toute la journée
- Idéale pour la maison, les visites et les fêtes', 'جبة طويلة وانسيابية، **تطريز على الياقة والأكمام**، قصة واسعة ومريحة.

- قماش خفيف ومريح طوال اليوم
- مثالية للبيت والزيارات والمناسبات', 'published', (SELECT id FROM categories WHERE slug = 'gandouras-djebbas-robes'), '["nouveaute"]', 5200, NULL, 2800, 18, 1791028500676, 1791028500676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (37, 19, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (99, 37, 'M', 'M', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (100, 37, 'L', 'L', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (101, 37, 'XL', 'XL', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (102, 37, 'XXL', 'XXL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (38, 19, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (103, 38, 'Bordeaux', 'خمري', '#6d1f33', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (104, 38, 'Champagne', 'شمبانيا', '#e9d3b0', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (123, 19, 'DJEBROLIL-BORDEAUX-M', '[99,103]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (124, 19, 'DJEBROLIL-BORDEAUX-L', '[100,103]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (125, 19, 'DJEBROLIL-BORDEAUX-XL', '[101,103]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (126, 19, 'DJEBROLIL-BORDEAUX-XXL', '[102,103]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (127, 19, 'DJEBROLIL-CHAMPAGNE-M', '[99,104]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (128, 19, 'DJEBROLIL-CHAMPAGNE-L', '[100,104]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (129, 19, 'DJEBROLIL-CHAMPAGNE-XL', '[101,104]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (130, 19, 'DJEBROLIL-CHAMPAGNE-XXL', '[102,104]', 2, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, published_at, updated_at) VALUES (20, 'gandoura-ete-kenza', 'Gandoura d''été Kenza', 'قندورة صيفية كنزة', 'Gandoura **en coton**, légère et fraîche, motifs discrets. Taille unique ample.', 'قندورة **من القطن**، خفيفة ومنعشة، بنقوش هادئة. مقاس واحد واسع.', 'published', (SELECT id FROM categories WHERE slug = 'gandouras-djebbas-robes'), '[]', 3500, NULL, 1700, 19, 1789905300676, 1789905300676, 1791201300676);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (39, 20, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (105, 39, 'Taille unique', 'مقاس واحد', NULL, 0);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (40, 20, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (106, 40, 'Bleu ciel', 'أزرق سماوي', '#a9c8e8', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (107, 40, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (131, 20, 'GANETEKEN-CIEL-TU', '[105,106]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (132, 20, 'GANETEKEN-ROSE-TU', '[105,107]', 6, 0, 2, 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (1, 'livraison-retours', 'Livraison & retours', 'التوصيل والإرجاع', '## Livraison

Nous livrons dans les **69 wilayas** d''Algérie avec notre partenaire **ZR Express**.

- **À domicile** : le livreur vous apporte le colis à l''adresse indiquée.
- **Au bureau (stop-desk)** : vous récupérez le colis au bureau ZR Express le plus proche, souvent moins cher.
- Le prix de la livraison dépend de votre wilaya et de votre commune : il s''affiche avant de valider la commande.

## Délais

- **1 à 3 jours** dans les wilayas du Nord
- **Jusqu''à 7 jours** dans les wilayas du Sud

Le délai commence après la confirmation de votre commande par téléphone.

## Paiement

Vous payez **en espèces à la réception** du colis, sans carte bancaire. Aucun paiement n''est demandé en ligne.

## Confirmation et suivi

- Après votre commande, notre équipe vous appelle pour la confirmer avant l''expédition. Merci de garder votre téléphone à portée de main.
- Suivez votre colis sur la page [Suivi de commande](/fr/suivi) avec votre numéro de téléphone, ou avec le lien privé reçu après la commande.
- Tant que la commande n''est pas confirmée, vous pouvez **modifier votre adresse ou annuler** depuis ce lien.

## Échange

La taille ne vous va pas ? **Contactez-nous dans les 48 h** suivant la réception et nous trouvons une solution ensemble.

- L''article doit être **non porté, non lavé**, avec ses étiquettes et dans son emballage d''origine.
- Pour des raisons d''hygiène, les pyjamas et vêtements de nuit déballés et portés ne peuvent pas être échangés.
- En cas d''article défectueux ou d''erreur de notre part, l''échange est **à nos frais**.

## Notre boutique

Vous pouvez aussi essayer et acheter sur place, dans notre boutique à **Dellys (Laqhaoui, à côté du tribunal)**, ouverte **7j/7**. Voir [l''adresse et les horaires](/fr/boutique).', '## التوصيل

نوصل إلى **69 ولاية** في الجزائر مع شريكنا **ZR Express**.

- **إلى المنزل**: يوصل لك المندوب الطرد إلى العنوان الذي تحددينه.
- **إلى المكتب (Stop-desk)**: تستلمين الطرد من أقرب مكتب ZR Express، وغالبًا بسعر أقل.
- سعر التوصيل حسب ولايتك وبلديتك، ويظهر لك قبل تأكيد الطلب.

## مدة التوصيل

- **من 1 إلى 3 أيام** في ولايات الشمال
- **حتى 7 أيام** في ولايات الجنوب

تبدأ المدة بعد تأكيد طلبك عبر الهاتف.

## الدفع

تدفعين **نقدًا عند استلام** الطرد، بدون بطاقة بنكية. لا نطلب أي دفع عبر الإنترنت.

## التأكيد والتتبع

- بعد طلبك، يتصل بك فريقنا لتأكيده قبل الشحن. من فضلك أبقي هاتفك قريبًا منك.
- تتبعي طردك من صفحة [تتبع طلباتي](/suivi) برقم هاتفك، أو بالرابط الخاص الذي يصلك بعد الطلب.
- ما دام الطلب لم يُؤكَّد بعد، يمكنك **تعديل العنوان أو إلغاء الطلب** من هذا الرابط.

## التبديل

المقاس غير مناسب؟ **تواصلي معنا خلال 48 ساعة** من الاستلام وسنجد الحل معًا.

- يجب أن تكون القطعة **غير ملبوسة وغير مغسولة**، بملصقاتها وفي تغليفها الأصلي.
- لأسباب صحية، لا يمكن تبديل البيجامات وملابس النوم بعد فتحها ولبسها.
- إذا كانت القطعة معيبة أو أخطأنا في طلبك، يكون التبديل **على حسابنا**.

## محلنا

يمكنك أيضًا القياس والشراء مباشرة في محلنا في **دلس (لقهاوي، بجانب المحكمة)**، المفتوح **7 أيام في الأسبوع**. شاهدي [العنوان وأوقات العمل](/boutique).', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (2, 'cgv', 'Conditions générales de vente', 'الشروط العامة للبيع', '## 1. Objet

Ces conditions s''appliquent à toutes les commandes passées sur le site Henine Boutique. Passer commande signifie les accepter.

## 2. Produits

Nous décrivons nos articles le plus fidèlement possible (photos, matière, tailles). De légères différences de couleur peuvent exister selon l''écran. Les disponibilités sont indiquées en temps réel ; si un article venait à manquer après votre commande, nous vous prévenons par téléphone.

## 3. Prix

- Les prix sont affichés en **dinars algériens (DA)**.
- Les **frais de livraison** s''ajoutent au prix des articles ; ils sont indiqués avant la validation de la commande.
- Les codes promo et promotions s''appliquent selon leurs conditions et leur durée.

## 4. Commande

- Vous commandez **sans créer de compte**, avec votre nom, votre numéro de téléphone et votre adresse.
- Chaque commande est **confirmée par téléphone** avant l''expédition. Une commande que nous ne parvenons pas à confirmer après plusieurs appels peut être annulée.
- Vous pouvez annuler ou modifier votre adresse tant que la commande n''est pas confirmée, depuis votre lien de suivi.
- Nous pouvons refuser une commande en cas de données manifestement fausses ou d''abus répétés.

## 5. Paiement

Le paiement se fait **en espèces à la livraison**, au livreur ou au bureau de retrait.

## 6. Livraison

La livraison est assurée par ZR Express dans les 69 wilayas, à domicile ou en bureau. Délais et détails : voir [Livraison & retours](/fr/p/livraison-retours).

## 7. Échanges

Un échange est possible dans les **48 h** suivant la réception, selon les conditions de la page [Livraison & retours](/fr/p/livraison-retours).

## 8. Données personnelles

Vos informations servent uniquement à traiter votre commande : voir la [Politique de confidentialité](/fr/p/confidentialite).

## 9. Contact

Pour toute question : la page [Contact](/fr/contact), ou notre boutique à Dellys. Ces conditions sont soumises au droit algérien.', '## 1. الموضوع

تنطبق هذه الشروط على كل الطلبات عبر موقع Henine Boutique. إتمام الطلب يعني الموافقة عليها.

## 2. المنتجات

نصف قطعنا بأكبر دقة ممكنة (الصور، القماش، المقاسات). قد يوجد فرق بسيط في اللون حسب الشاشة. التوفر يظهر مباشرة؛ وإذا نفدت قطعة بعد طلبك، نخبرك عبر الهاتف.

## 3. الأسعار

- الأسعار معروضة **بالدينار الجزائري (دج)**.
- **مصاريف التوصيل** تضاف إلى سعر القطع، وتظهر قبل تأكيد الطلب.
- تُطبَّق أكواد التخفيض والعروض حسب شروطها ومدتها.

## 4. الطلب

- تطلبين **بدون إنشاء حساب**، باسمك ورقم هاتفك وعنوانك.
- كل طلب **يُؤكَّد عبر الهاتف** قبل الشحن. قد يُلغى الطلب إذا تعذر تأكيده بعد عدة مكالمات.
- يمكنك إلغاء الطلب أو تعديل العنوان ما دام لم يُؤكَّد، من رابط التتبع الخاص بك.
- يمكننا رفض طلب إذا كانت المعلومات خاطئة بشكل واضح أو في حالة التكرار المسيء.

## 5. الدفع

يكون الدفع **نقدًا عند الاستلام**، للمندوب أو في مكتب الاستلام.

## 6. التوصيل

يتم التوصيل مع ZR Express إلى 69 ولاية، إلى المنزل أو إلى المكتب. المدة والتفاصيل في صفحة [التوصيل والإرجاع](/p/livraison-retours).

## 7. التبديل

التبديل ممكن خلال **48 ساعة** من الاستلام، حسب شروط صفحة [التوصيل والإرجاع](/p/livraison-retours).

## 8. المعطيات الشخصية

تُستعمل معلوماتك فقط لمعالجة طلبك: راجعي [سياسة الخصوصية](/p/confidentialite).

## 9. التواصل

لأي سؤال: صفحة [تواصلي معنا](/contact)، أو محلنا في دلس. تخضع هذه الشروط للقانون الجزائري.', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (3, 'confidentialite', 'Politique de confidentialité', 'سياسة الخصوصية', 'Henine Boutique protège vos données conformément à la **loi 18-07** relative à la protection des personnes physiques dans le traitement des données à caractère personnel.

## Ce que nous collectons

- **Pour une commande** : nom, numéro de téléphone, wilaya, commune, adresse et votre éventuelle note.
- **Commande non terminée** : si vous saisissez votre numéro au moment de commander sans finaliser, nous le gardons **30 jours** pour pouvoir vous recontacter, puis il est supprimé.
- **Avis et messages** : ce que vous écrivez dans un avis ou via la page Contact.
- **Sécurité** : une empreinte anonymisée de votre adresse IP, pour bloquer les fausses commandes, effacée après **90 jours**.

## À quoi elles servent

- Confirmer votre commande par téléphone, la préparer et la livrer.
- Vous informer du suivi de votre colis et répondre à vos messages.
- Lutter contre les fausses commandes et les abus.

Nous ne vendons et ne louons jamais vos données.

## Qui y a accès

- Notre équipe, pour traiter votre commande.
- **ZR Express**, notre transporteur : uniquement le nom, le téléphone et l''adresse nécessaires à la livraison.
- Notre hébergeur technique (Cloudflare), qui stocke le site et ses données de façon sécurisée.

## Sur votre téléphone

Votre panier, vos favoris et vos préférences (langue, mode sombre) sont enregistrés **sur votre propre téléphone**, pas chez nous. Les notifications (retour en stock, nouveautés) ne sont envoyées que si vous les acceptez, et vous pouvez les couper à tout moment.

## Vos droits

Vous pouvez demander à **consulter, corriger ou supprimer** vos données en nous écrivant depuis la page [Contact](/fr/contact).', 'تحمي Henine Boutique معطياتك وفقًا **للقانون 18-07** المتعلق بحماية الأشخاص الطبيعيين في مجال معالجة المعطيات ذات الطابع الشخصي.

## ما الذي نجمعه

- **عند الطلب**: الاسم، رقم الهاتف، الولاية، البلدية، العنوان وملاحظتك إن وُجدت.
- **طلب لم يكتمل**: إذا كتبتِ رقمك أثناء الطلب دون إتمامه، نحتفظ به **30 يومًا** لنتمكن من التواصل معك، ثم يُحذف.
- **الآراء والرسائل**: ما تكتبينه في رأي أو عبر صفحة التواصل.
- **الأمان**: بصمة مجهولة لعنوان IP الخاص بك لمنع الطلبات الوهمية، تُحذف بعد **90 يومًا**.

## لماذا نستعملها

- لتأكيد طلبك عبر الهاتف وتحضيره وتوصيله.
- لإعلامك بتتبع طردك والرد على رسائلك.
- لمحاربة الطلبات الوهمية والاستعمال المسيء.

لا نبيع معطياتك ولا نؤجرها أبدًا.

## من يطّلع عليها

- فريقنا، لمعالجة طلبك.
- **ZR Express**، شركة التوصيل: فقط الاسم والهاتف والعنوان اللازمة للتوصيل.
- مزود الاستضافة التقني (Cloudflare)، الذي يحفظ الموقع ومعطياته بشكل آمن.

## على هاتفك

سلتك ومفضلتك وتفضيلاتك (اللغة، الوضع الداكن) محفوظة **على هاتفك أنتِ**، وليس عندنا. الإشعارات (عودة قطعة إلى المخزون، الجديد) لا تُرسل إلا إذا وافقتِ عليها، ويمكنك إيقافها في أي وقت.

## حقوقك

يمكنك طلب **الاطلاع على معطياتك أو تصحيحها أو حذفها** بمراسلتنا من صفحة [تواصلي معنا](/contact).', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (4, 'a-propos', 'À propos', 'من نحن', '## Henine Boutique

**L''élégance et la qualité au meilleur prix.** Henine Boutique, c''est une boutique de mode féminine née à Dellys, dans la wilaya de Boumerdès : robes, djebbas et pyjamas choisis pour leur tombé, leur confort et leurs finitions.

## Notre promesse

- **Des pièces choisies une à une**, de belles matières à des prix justes.
- **Commander simplement** : sans compte, paiement à la livraison.
- **Partout en Algérie** : livraison dans les 69 wilayas, à domicile ou en bureau.
- **Une vraie équipe** qui vous appelle pour confirmer votre commande et vous conseiller sur la taille.

## Venez nous voir

Notre boutique vous accueille **7j/7** à **Dellys (Laqhaoui, à côté du tribunal)**. Venez essayer vos pièces préférées : [adresse et horaires](/fr/boutique).

Suivez nos nouveautés et nos essayages en vidéo sur Instagram.', '## Henine Boutique

**الأناقة والجودة بأفضل سعر.** Henine Boutique محل أزياء نسائية وُلد في دلس، ولاية بومرداس: فساتين، جبات وبيجامات نختارها لانسدالها وراحتها وجودة تفاصيلها.

## وعدنا

- **قطع نختارها واحدة واحدة**، بأقمشة جميلة وأسعار معقولة.
- **طلب سهل**: بدون حساب، والدفع عند الاستلام.
- **في كل الجزائر**: توصيل إلى 69 ولاية، إلى المنزل أو إلى المكتب.
- **فريق حقيقي** يتصل بك لتأكيد طلبك وينصحك في اختيار المقاس.

## زوري محلنا

محلنا يستقبلك **7 أيام في الأسبوع** في **دلس (لقهاوي، بجانب المحكمة)**. تعالي وقيسي قطعك المفضلة: [العنوان وأوقات العمل](/boutique).

تابعي جديدنا وقياساتنا بالفيديو على إنستغرام.', 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (1, 'bio', NULL, '🛍️ Voir la boutique', '🛍️ تصفحي المتجر', '/', 'shop', 0, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (2, 'bio', NULL, '📦 Suivre ma commande', '📦 تتبع طلبي', '/suivi', 'package', 1, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (3, 'bio', NULL, '📸 Instagram', '📸 إنستغرام', 'https://www.instagram.com/henine.boutique/', 'instagram', 2, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (4, 'bio', NULL, '📍 Nous contacter', '📍 تواصلي معنا', '/contact', 'pin', 3, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (5, 'short', 'insta', 'Instagram bio', 'Instagram bio', '/?utm_source=instagram&utm_medium=bio', NULL, 4, 1);
INSERT OR IGNORE INTO coupons (code, type, value, min_subtotal, is_active) VALUES ('BIENVENUE10', 'percent', 10, 3000, 1);
INSERT OR REPLACE INTO settings (key, value) VALUES ('catalog_version', '1791201300676');
