-- Generated by packages/db/scripts/build-demo-seed.mjs: DEMO DATA, safe to re-run.
PRAGMA defer_foreign_keys = on;
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (1, 'robe-satin-nour', 'Robe satin Nour', 'فستان ساتان نور', 'Robe longue en **satin fluide**, coupe portefeuille et ceinture à nouer.

- Tissu doux et léger
- Tombé élégant, idéale pour les fêtes
- Lavage délicat à 30°', 'فستان طويل من **الساتان الناعم**، بقصة ملفوفة وحزام للربط.

- قماش ناعم وخفيف
- انسدال أنيق، مثالي للمناسبات
- غسيل لطيف على 30 درجة', 'published', (SELECT id FROM categories WHERE slug = 'robes'), '["nouveaute","best-seller"]', 4900, 6500, 2600, 0, 1790797903693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (1, 1, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (1, 1, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (2, 1, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (3, 1, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (4, 1, 'XL', 'XL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (2, 1, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (5, 2, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (6, 2, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (7, 2, 'Émeraude', 'زمردي', '#1f6f5c', 2);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (1, 1, 'NOUR-ROSE-S', '[1,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (2, 1, 'NOUR-ROSE-M', '[2,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (3, 1, 'NOUR-ROSE-L', '[3,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (4, 1, 'NOUR-ROSE-XL', '[4,5]', 6, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (5, 1, 'NOUR-NOIR-S', '[1,6]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (6, 1, 'NOUR-NOIR-M', '[2,6]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (7, 1, 'NOUR-NOIR-L', '[3,6]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (8, 1, 'NOUR-NOIR-XL', '[4,6]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (9, 1, 'NOUR-EMERAUDE-S', '[1,7]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (10, 1, 'NOUR-EMERAUDE-M', '[2,7]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (11, 1, 'NOUR-EMERAUDE-L', '[3,7]', 3, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (12, 1, 'NOUR-EMERAUDE-XL', '[4,7]', 0, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (2, 'robe-fleurie-yasmine', 'Robe fleurie Yasmine', 'فستان مزهر ياسمين', 'Robe midi à **imprimé fleuri**, manches bouffantes et col carré. Parfaite pour le printemps.', 'فستان متوسط الطول **بطبعة زهور**، أكمام منفوخة وياقة مربعة. مثالي للربيع.', 'published', (SELECT id FROM categories WHERE slug = 'robes'), '["nouveaute"]', 3900, NULL, 2000, 1, 1790794303693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (3, 2, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (8, 3, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (9, 3, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (10, 3, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (4, 2, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (11, 4, 'Blanc fleuri', 'أبيض مزهر', '#f4efe9', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (12, 4, 'Bleu ciel', 'أزرق سماوي', '#a9c8e8', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (13, 2, 'YASMINE-BLANC-S', '[8,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (14, 2, 'YASMINE-BLANC-M', '[9,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (15, 2, 'YASMINE-BLANC-L', '[10,11]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (16, 2, 'YASMINE-CIEL-S', '[8,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (17, 2, 'YASMINE-CIEL-M', '[9,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (18, 2, 'YASMINE-CIEL-L', '[10,12]', 4, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (3, 'pyjama-satin-lina', 'Pyjama satin Lina', 'بيجامة ساتان لينا', 'Ensemble chemise + pantalon en **satin**, passepoil contrasté. Confort et élégance pour vos nuits.', 'طقم قميص + سروال من **الساتان** بحواف متباينة. راحة وأناقة لليالي.', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas'), '["best-seller"]', 3500, 4200, 1700, 2, 1790790703693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (5, 3, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (13, 5, 'M', 'M', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (14, 5, 'L', 'L', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (15, 5, 'XL', 'XL', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (6, 3, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (16, 6, 'Champagne', 'شمبانيا', '#e9d3b0', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (17, 6, 'Bordeaux', 'خمري', '#6d1f33', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (19, 3, 'LINA-CHAMPAGNE-M', '[13,16]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (20, 3, 'LINA-CHAMPAGNE-L', '[14,16]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (21, 3, 'LINA-CHAMPAGNE-XL', '[15,16]', 1, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (22, 3, 'LINA-BORDEAUX-M', '[13,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (23, 3, 'LINA-BORDEAUX-L', '[14,17]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (24, 3, 'LINA-BORDEAUX-XL', '[15,17]', 1, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (4, 'pyjama-coton-doux', 'Pyjama coton Doux', 'بيجامة قطن ناعمة', 'Pyjama 100 % coton, **ultra doux**, pantalon à taille élastique.', 'بيجامة قطن 100%، **ناعمة جدا**، سروال بخصر مطاطي.', 'published', (SELECT id FROM categories WHERE slug = 'pyjamas'), '[]', 2800, NULL, 1300, 3, 1790787103693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (7, 4, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (18, 7, 'M', 'M', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (19, 7, 'L', 'L', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (20, 7, 'XL', 'XL', NULL, 2);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (21, 7, 'XXL', 'XXL', NULL, 3);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (8, 4, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (22, 8, 'Lavande', 'لافندر', '#b9a7d6', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (23, 8, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (25, 4, 'DOUX-LAVANDE-M', '[18,22]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (26, 4, 'DOUX-LAVANDE-L', '[19,22]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (27, 4, 'DOUX-LAVANDE-XL', '[20,22]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (28, 4, 'DOUX-LAVANDE-XXL', '[21,22]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (29, 4, 'DOUX-ROSE-M', '[18,23]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (30, 4, 'DOUX-ROSE-L', '[19,23]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (31, 4, 'DOUX-ROSE-XL', '[20,23]', 8, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (32, 4, 'DOUX-ROSE-XXL', '[21,23]', 8, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (5, 'ensemble-dentelle-rose', 'Ensemble dentelle Rose', 'طقم دانتيل روز', 'Ensemble soutien-gorge + culotte en **dentelle délicate**. Livré dans un emballage discret.', 'طقم حمالة صدر + سروال داخلي من **الدانتيل الرقيق**. يصلك في تغليف سري.', 'published', (SELECT id FROM categories WHERE slug = 'lingerie'), '["nouveaute"]', 2900, 3500, 1200, 4, 1790783503693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (9, 5, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (24, 9, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (25, 9, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (26, 9, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (10, 5, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (27, 10, 'Rose poudré', 'وردي فاتح', '#e8b4bc', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (28, 10, 'Noir', 'أسود', '#1f1a1c', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (33, 5, 'ROSE-ROSE-S', '[24,27]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (34, 5, 'ROSE-ROSE-M', '[25,27]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (35, 5, 'ROSE-ROSE-L', '[26,27]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (36, 5, 'ROSE-NOIR-S', '[24,28]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (37, 5, 'ROSE-NOIR-M', '[25,28]', 5, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (38, 5, 'ROSE-NOIR-L', '[26,28]', 5, 0, 2, 1);
INSERT OR REPLACE INTO products (id, slug, name_fr, name_ar, description_fr, description_ar, status, category_id, tags, price, compare_at_price, cost_price, sort, created_at, updated_at) VALUES (6, 'nuisette-soie-amira', 'Nuisette Amira', 'قميص نوم أميرة', 'Nuisette **satinée** à fines bretelles réglables, bordure en dentelle.', 'قميص نوم **ساتان** بحمالات رفيعة قابلة للتعديل وحواف من الدانتيل.', 'published', (SELECT id FROM categories WHERE slug = 'lingerie'), '[]', 2500, NULL, 1000, 5, 1790779903693, 1790797903693);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (11, 6, 'taille', 'Taille', 'المقاس', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (29, 11, 'S', 'S', NULL, 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (30, 11, 'M', 'M', NULL, 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (31, 11, 'L', 'L', NULL, 2);
INSERT OR REPLACE INTO product_options (id, product_id, kind, name_fr, name_ar, sort) VALUES (12, 6, 'couleur', 'Couleur', 'اللون', 1);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (32, 12, 'Bordeaux', 'خمري', '#6d1f33', 0);
INSERT OR REPLACE INTO option_values (id, option_id, label_fr, label_ar, hex, sort) VALUES (33, 12, 'Champagne', 'شمبانيا', '#e9d3b0', 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (39, 6, 'AMIRA-BORDEAUX-S', '[29,32]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (40, 6, 'AMIRA-BORDEAUX-M', '[30,32]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (41, 6, 'AMIRA-BORDEAUX-L', '[31,32]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (42, 6, 'AMIRA-CHAMPAGNE-S', '[29,33]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (43, 6, 'AMIRA-CHAMPAGNE-M', '[30,33]', 2, 0, 2, 1);
INSERT OR REPLACE INTO variants (id, product_id, sku, option_value_ids, stock_on_hand, stock_reserved, low_stock_threshold, is_active) VALUES (44, 6, 'AMIRA-CHAMPAGNE-L', '[31,33]', 2, 0, 2, 1);
INSERT OR REPLACE INTO reviews (id, product_id, name, rating, text, verified, status, created_at) VALUES (1, 1, 'Amina', 5, 'Magnifique robe, le satin est de très bonne qualité. Livraison rapide à Alger !', 1, 'approved', 1790538703693);
INSERT OR REPLACE INTO reviews (id, product_id, name, rating, text, verified, status, created_at) VALUES (2, 1, 'Sara', 4, 'Très jolie, taille un peu grand. Je conseille de prendre une taille en dessous.', 1, 'approved', 1790106703693);
INSERT OR REPLACE INTO reviews (id, product_id, name, rating, text, verified, status, created_at) VALUES (3, 3, 'نسرين', 5, 'بيجامة رائعة وناعمة جدا، شكرا Henine', 1, 'approved', 1790365903693);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (1, 'livraison-retours', 'Livraison & retours', 'التوصيل والإرجاع', '## Livraison

Nous livrons dans les **69 wilayas** avec ZR Express, à domicile ou en bureau (stop-desk).

- Délai : 1 à 7 jours selon la wilaya
- Paiement à la livraison

## Échange

Taille pas parfaite ? Contactez-nous sous 48 h après réception pour un échange.', '## التوصيل

نوصل إلى **69 ولاية** مع ZR Express، إلى المنزل أو إلى المكتب.

- المدة: من 1 إلى 7 أيام حسب الولاية
- الدفع عند الاستلام

## التبديل

المقاس غير مناسب؟ اتصلي بنا خلال 48 ساعة من الاستلام للتبديل.', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (2, 'cgv', 'Conditions générales de vente', 'الشروط العامة للبيع', '## Commandes

Toute commande est confirmée par téléphone avant expédition.

## Prix

Les prix sont indiqués en dinars algériens (DA), frais de livraison en plus.', '## الطلبات

يتم تأكيد كل طلب عبر الهاتف قبل الشحن.

## الأسعار

الأسعار بالدينار الجزائري، مصاريف التوصيل إضافية.', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (3, 'confidentialite', 'Politique de confidentialité', 'سياسة الخصوصية', 'Vos données (nom, téléphone, adresse) servent uniquement à traiter et livrer votre commande, conformément à la loi 18-07 sur la protection des données personnelles.', 'تُستخدم بياناتك (الاسم، الهاتف، العنوان) فقط لمعالجة طلبك وتوصيله، وفقا للقانون 18-07 المتعلق بحماية المعطيات الشخصية.', 1);
INSERT OR REPLACE INTO pages (id, slug, title_fr, title_ar, body_fr, body_ar, is_active) VALUES (4, 'a-propos', 'À propos', 'من نحن', 'Henine Boutique, c''est **l''élégance et la qualité au meilleur prix**. Notre boutique vous accueille à Boumerdès 7j/7.', 'Henine Boutique هي **الأناقة والجودة بأفضل سعر**. محلنا في بومرداس يستقبلكم 7 أيام في الأسبوع.', 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (1, 'bio', NULL, '🛍️ Voir la boutique', '🛍️ تصفحي المتجر', '/', 'shop', 0, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (2, 'bio', NULL, '📦 Suivre ma commande', '📦 تتبع طلبي', '/suivi', 'package', 1, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (3, 'bio', NULL, '📸 Instagram', '📸 إنستغرام', 'https://www.instagram.com/henine.boutique/', 'instagram', 2, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (4, 'bio', NULL, '📍 Nous contacter', '📍 تواصلي معنا', '/contact', 'pin', 3, 1);
INSERT OR REPLACE INTO links (id, kind, slug, label_fr, label_ar, target, icon, sort, is_active) VALUES (5, 'short', 'insta', 'Instagram bio', 'Instagram bio', '/?utm_source=instagram&utm_medium=bio', NULL, 4, 1);
INSERT OR IGNORE INTO coupons (code, type, value, min_subtotal, is_active) VALUES ('BIENVENUE10', 'percent', 10, 3000, 1);
INSERT OR REPLACE INTO settings (key, value) VALUES ('catalog_version', '1790797903693');
